version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  linuxBuild:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      # - checkout # check out the code in the project directory
      - run: echo "hello linux"
  macBuild:
    macos:
      xcode: "11.3.0"
    steps:
      # - checkout # check out the code in the project directory
      - run: echo "hello mac"
  winBuild:
    executor: win/default
    steps:
      # - checkout # check out the code in the project directory
      - run: echo "hello windows"

workflows:
  version: 2
  build_and_test:
    jobs:
      - linuxBuild
      - macBuild
      - winBuild